server:
  port: 8082
  name: user-edge-service

thrift:
  user:
    ip: 127.0.0.1
    port: 7911
  message:
    ip: 127.0.0.1
    port: 9090
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 30000